package com.smartloadout;

public enum LoadoutRuleType
{
    REQUIRED_ITEM,
    MINIMUM_QUANTITY,
    REQUIRED_SPELLBOOK,
    RUNE_POUCH_CONTAINS,
    AMMO_OR_RANGED_WEAPON,
    ATTACK_STYLE,
    TELEPORT_CATEGORY,
    WILDERNESS_TELEPORT_LIMIT,
    DUPLICATE_SUPPLY_WARNING
}
